#!/usr/bin/env python3
# SPDX-License-Identifier: FSL-1.1-ALv2
"""Operator-provenance classification for the chat-history signal reducer.

Answers one question for ``extract-chat-signal.py``: **is this ``user`` turn
operator-authored, or did the harness inject it?** The contract it implements —
why the predicate is positive rather than an enumeration, which envelopes carry
operator content, and the published marker inventory with its residual gap — is
specified in ``references/chat-history-analysis.md`` and is not restated here.

Split from the reducer so the classification rules can be read and tested on
their own; the reducer keeps the walk, the counters and the output contract.
"""

from __future__ import annotations

import re

# Structural signature of a synthetic skill-load turn: the harness injects a
# loaded skill's body as a ``user`` turn whose text opens with the base-directory
# line and continues into the skill's markdown body.
_SKILL_LOAD_MARKER = 'Base directory for this skill:'
_MARKDOWN_HEADING_RE = re.compile(r'^#{1,6}\s+\S', re.MULTILINE)

# One XML-ish tag. Envelopes are recognised GENERICALLY over the tag name —
# the point being that a wrapper introduced after this file was written is
# still recognised, which is exactly what an enumeration of known tag names
# cannot do.
#
# ⚠ Deliberately matches ONE TAG, not a whole block. A single-regex
# ``<tag>.*?</tag>`` pattern is quadratic on a transcript carrying unmatched
# ``<`` markup: every unmatched open tag rescans to end-of-text before failing.
# Measured at 0.5 s for 0.06 MB of unclosed tags, which extrapolates to minutes
# at the 2 MiB read budget — a hang in a pre-pass whose whole purpose is to be
# cheap. :func:`strip_harness_envelopes` pairs these tokens in a single linear
# pass instead.
_TAG_RE = re.compile(r'<(?P<close>/)?(?P<tag>[A-Za-z][-\w.]*)(?P<attrs>[^<>]*)>')

# Verbatim harness notices that carry NO envelope at all, matched as literal
# prefixes of the residue because there is no tag to key on.
#
# ⚠ This list is a SAMPLE and is known to be incomplete — it is a backstop, not
# the mechanism. The structural predicate covers every tag-wrapped injection
# including shapes nobody has seen; a tagless notice can only be recognised by
# its words, so each entry here is an observed shape and a new one is a miss
# until it is added. `references/chat-history-analysis.md` publishes the
# residual gap rather than implying this list is closed.
HARNESS_NOTICE_PREFIXES: tuple[str, ...] = (
    'This session is being continued from a previous conversation',
    'Caveat: The messages below were generated by the user while running local commands',
    'Stop hook feedback:',
)

# Harness envelopes whose CONTENT is operator-authored. The wrapper is the
# harness's; the text inside is the operator's, so the inner text is kept as
# residue instead of being stripped with the envelope. A slash command is the
# case that matters here: the operator's whole instruction rides inside
# ``<command-args>``, and dropping the envelope wholesale discards the primary
# channel through which this project's operators drive a run.
#
# This is an allow-list, and it is safe in the direction an allow-list can be:
# an operator-bearing envelope nobody listed reads as synthetic, never the
# reverse.
OPERATOR_BEARING_TAGS: frozenset[str] = frozenset({'command-args'})


def is_synthetic_skill_load(text: str) -> bool:
    """Return True when ``text`` is a skill body injected as a synthetic user turn.

    Recognized structurally rather than by any single substring: the text must
    carry the ``Base directory for this skill:`` line AND a markdown heading
    somewhere after it — the shape of an injected SKILL.md body. Requiring both
    keeps an operator who merely quotes the marker line from being dropped.
    """
    index = text.find(_SKILL_LOAD_MARKER)
    if index == -1:
        return False
    return _MARKDOWN_HEADING_RE.search(text, index) is not None


def partition_turn(text: str) -> tuple[str, str]:
    """Split ``text`` into (residue, text recovered from operator-bearing envelopes).

    The residue is what an operator wrote OUTSIDE the harness's envelopes. The
    harness routinely attaches an envelope to a genuine operator turn, so a
    turn is synthetic only when the residue is empty — not merely because an
    envelope is present.

    Three rules make the residue trustworthy:

    * Only a MATCHED open/close pair is an envelope. Stray markup in operator
      prose stays in the residue rather than swallowing the rest of the turn.
    * Only the OUTERMOST pair is removed; a nested pair is already inside it.
      An unmatched open tag earlier in the turn therefore cannot suppress the
      stripping of a well-formed envelope that follows it — a fail-toward-
      *operator* path, the direction that manufactures a false clean verdict.
    * An envelope named in :data:`OPERATOR_BEARING_TAGS` contributes its INNER
      text to the residue, because the wrapper is the harness's but the words
      inside it are the operator's.

    The second element is only the operator-bearing text, returned separately
    so a caller can tell *"prose survived"* from *"the operator typed a command"*
    — :func:`is_operator_authored` needs that distinction, because a harness
    notice opening the turn must not veto an instruction the operator explicitly
    entered later in it.

    Runs in one linear pass: tags are tokenized once and paired through a
    stack, with an index from tag name to its open positions so a close tag
    pairs in amortized constant time. No pattern ever rescans the text.
    """
    stack: list[tuple[str, int, int]] = []
    open_positions: dict[str, list[int]] = {}
    pairs: list[tuple[int, int, str, int, int]] = []

    def _drop_above(depth: int) -> None:
        """Discard stack entries at or above ``depth``, keeping the index in step."""
        for tag, _, _ in stack[depth:]:
            positions = open_positions.get(tag)
            if positions:
                positions.pop()
        del stack[depth:]

    for token in _TAG_RE.finditer(text):
        tag = token.group('tag')
        if token.group('close'):
            positions = open_positions.get(tag)
            if not positions:
                continue  # An unmatched close tag is ordinary text.
            depth = positions[-1]
            _, block_start, inner_start = stack[depth]
            _drop_above(depth)
            pairs.append((block_start, token.end(), tag, inner_start, token.start()))
        elif token.group('attrs').endswith('/'):
            pairs.append((token.start(), token.end(), tag, token.end(), token.end()))
        else:
            open_positions.setdefault(tag, []).append(len(stack))
            stack.append((tag, token.start(), token.end()))

    if not pairs:
        return text, ''

    # By start position: an outer pair opens before the pair it contains, so the
    # cursor below skips the nested one. Starts are unique — each open token
    # yields at most one pair — so no tiebreak is needed.
    pairs.sort(key=lambda pair: pair[0])
    parts: list[str] = []
    recovered: list[str] = []
    cursor = 0
    for block_start, block_end, tag, inner_start, inner_end in pairs:
        if block_start < cursor:
            continue
        parts.append(text[cursor:block_start])
        if tag in OPERATOR_BEARING_TAGS:
            inner = text[inner_start:inner_end]
            parts.append(inner)
            recovered.append(inner)
        cursor = block_end
    parts.append(text[cursor:])
    return ''.join(parts), ''.join(recovered)


def strip_harness_envelopes(text: str) -> str:
    """Return ``text`` with every harness-injected tag block removed.

    The residue in document order — what :func:`partition_turn` returns first.
    """
    return partition_turn(text)[0]


def is_harness_notice(text: str) -> bool:
    """Return True when ``text`` opens with a verbatim, envelope-less harness notice.

    Anchored at the start deliberately: a notice IS the turn. Matching anywhere
    would drop an operator turn that merely quotes one.
    """
    head = text.lstrip()
    return any(head.startswith(notice) for notice in HARNESS_NOTICE_PREFIXES)


def is_operator_authored(text: str) -> bool:
    """Return True when ``text`` carries operator-authored prose.

    The positive predicate behind the whole reduction: rather than asking
    "does this match a known synthetic shape?" — which admits every shape
    nobody enumerated — it asks whether operator prose SURVIVES once the
    harness's own injection markers are removed. A turn with no residue is
    synthetic, whatever wrapper produced it.

    Non-whitespace text recovered from an operator-bearing envelope settles the
    question on its own; whitespace alone is not content, so a blank
    ``<command-args>`` leaves the turn to be judged on its residue.
    The notice check runs on the residue, and the residue carries that
    recovered text, so a turn opening with a harness notice and continuing into
    a slash command would otherwise be discarded — taking the operator's
    instruction with it.
    """
    if not text.strip():
        return False
    if is_synthetic_skill_load(text):
        return False
    residue, operator_bearing = partition_turn(text)
    if operator_bearing.strip():
        return True
    if not residue.strip():
        return False
    return not is_harness_notice(residue)

