# SPDX-License-Identifier: FSL-1.1-ALv2
"""Bundle mirror for the Claude target.

Walks ``marketplace/bundles/{bundle}/**`` and copies content byte-for-byte
into ``{output_dir}/{bundle}/``. Excludes ephemeral / generated files
(``__pycache__``, ``.pytest_cache``) and the bundle's
``.claude-plugin/plugin.json`` (the latter is regenerated by
``plugin_json_gen.py``).

Agent files declaring ``implements:
plan-marshall:extension-api/standards/ext-point-dynamic-level-executor``
are routed through ``variant_emitter`` instead of being copied
byte-for-byte: the canonical no-suffix file is emitted with
``implements:`` and ``levels:`` stripped, and per-level variants
(``{base}-{level}.md``) are produced alongside it. See
``variant_emitter.py`` for the variant-emission contract.

A component declaring a ``targets:`` frontmatter scope that omits this
target is not mirrored at all — see ``component_targets.py``. Its
manifest entry is dropped in lock-step by ``plugin_json_gen``, so the
equality check sees a deliberately-absent component rather than drift.
"""

from __future__ import annotations

import shutil
from collections.abc import Iterable, Iterator
from pathlib import Path

from marketplace.targets.claude.variant_emitter import (
    VariantEmissionResult,
    emit_variants_for_agent,
)
from marketplace.targets.component_targets import excluded_emission_roots, is_under_any
from marketplace.targets.fs_safety import is_within, safe_rmtree

#: This target's registry name — the value a component's ``targets:``
#: declaration must contain for the Claude target to emit it. Defined here
#: rather than on the target class because the emitter is the first module
#: that needs it, and importing the class from ``target.py`` (which imports
#: this module) would close a cycle.
CLAUDE_TARGET_NAME = 'claude'

EXCLUDED_DIR_NAMES = frozenset({'__pycache__', '.pytest_cache', '.mypy_cache', '.ruff_cache'})

# The plugin.json file is regenerated by plugin_json_gen.py so the
# verbatim emitter intentionally skips it.
EXCLUDED_RELATIVE_FILES = frozenset({Path('.claude-plugin') / 'plugin.json'})

# Path to the OpenCode mapping file (reused by the Claude target's
# max build-time guard to consult model_map alias→ID resolution).
_OPENCODE_MAPPING = Path(__file__).resolve().parent.parent / 'opencode' / 'mapping.json'


def iter_bundle_dirs(marketplace_dir: Path, bundles: list[str] | None) -> Iterator[Path]:
    """Yield bundle directories under ``marketplace_dir``.

    A directory qualifies as a bundle when it contains
    ``.claude-plugin/plugin.json``. The optional ``bundles`` list scopes
    the iteration to specific bundle names.
    """
    if not marketplace_dir.exists():
        return
    candidates = sorted(p for p in marketplace_dir.iterdir() if p.is_dir())
    for candidate in candidates:
        if bundles is not None and candidate.name not in bundles:
            continue
        if not (candidate / '.claude-plugin' / 'plugin.json').exists():
            continue
        yield candidate


def _is_excluded(rel: Path) -> bool:
    if rel in EXCLUDED_RELATIVE_FILES:
        return True
    parts = rel.parts
    return any(part in EXCLUDED_DIR_NAMES for part in parts)


def _is_agent_file(rel: Path) -> bool:
    return (
        len(rel.parts) == 2
        and rel.parts[0] == 'agents'
        and rel.suffix == '.md'
    )


def emit_bundle_verbatim(
    bundle_dir: Path,
    output_dir: Path,
    *,
    target_name: str = CLAUDE_TARGET_NAME,
) -> list[Path]:
    """Mirror ``bundle_dir`` into ``output_dir/{bundle_name}/``.

    Most files copy byte-for-byte. Agent files (``agents/*.md``) that
    declare the dynamic-level-executor extension point go through
    ``emit_variants_for_agent``: the canonical no-suffix variant gets
    written with role-fields stripped, and per-level variants are
    emitted alongside it.

    Returns the list of paths written under the destination directory.
    Skips entries listed in ``EXCLUDED_DIR_NAMES`` and
    ``EXCLUDED_RELATIVE_FILES``, plus every component whose ``targets:``
    frontmatter scope omits ``target_name`` (a skill's declaration
    governs its whole directory).

    Raises:
        TargetScopeError: Some component in the bundle declares an
            invalid ``targets:`` scope.

    The destination bundle directory is wiped before writing so stale
    artifacts from prior emits (e.g. variant files for source canonicals
    that have since been removed) do not linger. The wipe is **guarded**,
    not assumed safe: it is refused outright when the resolved destination
    lies inside the source tree (``bundle_dir.parent``), and
    :func:`safe_rmtree` independently refuses any target outside the
    resolved ``output_dir``. Gitignored-ness of the intended
    ``target/claude/`` destination is NOT the safeguard — that reasoning
    holds only for the intended path and says nothing about a mistyped
    ``output_dir`` pointing at real source, which the source-tree guard
    below refuses before a single byte is deleted. The top-level
    ``target/claude/.claude-plugin/`` directory holding the marketplace.json
    sits outside any per-bundle dir and is untouched.
    """
    bundle_name = bundle_dir.name
    dest_root = output_dir / bundle_name
    # Refuse to wipe a destination that overlaps the source tree: a mistyped
    # ``output_dir`` pointing at ``marketplace/bundles`` would otherwise make
    # ``dest_root`` the bundle's own source dir and this wipe destroy it.
    source_root = bundle_dir.parent
    if is_within(dest_root, source_root):
        raise ValueError(
            f'Refusing to wipe {dest_root.resolve()}: it lies inside the source tree '
            f'{source_root.resolve()} — the output directory must be a distinct build '
            'location, not the marketplace source'
        )
    if dest_root.exists():
        safe_rmtree(dest_root, output_dir)
    dest_root.mkdir(parents=True, exist_ok=True)

    scoped_out = excluded_emission_roots(bundle_dir, target_name)

    written: list[Path] = []
    for source in sorted(bundle_dir.rglob('*')):
        if not source.is_file():
            continue
        rel = source.relative_to(bundle_dir)
        if _is_excluded(rel) or is_under_any(rel, scoped_out):
            continue
        dest = dest_root / rel
        dest.parent.mkdir(parents=True, exist_ok=True)

        # Route role-eligible agents through variant emission.
        if _is_agent_file(rel):
            result: VariantEmissionResult | None = emit_variants_for_agent(
                source, dest, _OPENCODE_MAPPING
            )
            if result is not None:
                written.append(result.canonical_path)
                base_name = result.canonical_path.stem
                for level in result.variants_emitted:
                    written.append(result.canonical_path.with_name(f'{base_name}-{level}.md'))
                continue

        shutil.copyfile(source, dest)
        written.append(dest)
    return written


def emit_bundles_verbatim(
    marketplace_dir: Path,
    output_dir: Path,
    bundles: Iterable[str] | None = None,
    *,
    target_name: str = CLAUDE_TARGET_NAME,
) -> list[Path]:
    """Convenience wrapper — mirror every selected bundle."""
    bundle_list = list(bundles) if bundles is not None else None
    written: list[Path] = []
    for bundle_dir in iter_bundle_dirs(marketplace_dir, bundle_list):
        written.extend(emit_bundle_verbatim(bundle_dir, output_dir, target_name=target_name))
    return written
