"""Verbatim bundle mirror for the Claude target.

Walks ``marketplace/bundles/{bundle}/**`` and copies content byte-for-byte
into ``{output_dir}/{bundle}/``. Excludes ephemeral / generated files
(``__pycache__``, ``.pytest_cache``) and the bundle's
``.claude-plugin/plugin.json`` (the latter is regenerated by
``plugin_json_gen.py``).
"""

from __future__ import annotations

import shutil
from collections.abc import Iterable, Iterator
from pathlib import Path

EXCLUDED_DIR_NAMES = frozenset({'__pycache__', '.pytest_cache', '.mypy_cache', '.ruff_cache'})

# The plugin.json file is regenerated by plugin_json_gen.py so the
# verbatim emitter intentionally skips it.
EXCLUDED_RELATIVE_FILES = frozenset({Path('.claude-plugin') / 'plugin.json'})


def iter_bundle_dirs(marketplace_dir: Path, bundles: list[str] | None) -> Iterator[Path]:
    """Yield bundle directories under ``marketplace_dir``.

    A directory qualifies as a bundle when it contains
    ``.claude-plugin/plugin.json``. The optional ``bundles`` list scopes
    the iteration to specific bundle names.
    """
    if not marketplace_dir.exists():
        return
    candidates = sorted(p for p in marketplace_dir.iterdir() if p.is_dir())
    for candidate in candidates:
        if bundles is not None and candidate.name not in bundles:
            continue
        if not (candidate / '.claude-plugin' / 'plugin.json').exists():
            continue
        yield candidate


def _is_excluded(rel: Path) -> bool:
    if rel in EXCLUDED_RELATIVE_FILES:
        return True
    parts = rel.parts
    return any(part in EXCLUDED_DIR_NAMES for part in parts)


def emit_bundle_verbatim(bundle_dir: Path, output_dir: Path) -> list[Path]:
    """Mirror ``bundle_dir`` byte-for-byte into ``output_dir/{bundle_name}/``.

    Returns the list of paths written under the destination directory.
    Skips entries listed in ``EXCLUDED_DIR_NAMES`` and
    ``EXCLUDED_RELATIVE_FILES``.
    """
    bundle_name = bundle_dir.name
    dest_root = output_dir / bundle_name
    dest_root.mkdir(parents=True, exist_ok=True)

    written: list[Path] = []
    for source in sorted(bundle_dir.rglob('*')):
        if not source.is_file():
            continue
        rel = source.relative_to(bundle_dir)
        if _is_excluded(rel):
            continue
        dest = dest_root / rel
        dest.parent.mkdir(parents=True, exist_ok=True)
        shutil.copyfile(source, dest)
        # Preserve mtime to keep equality / staleness comparisons honest.
        shutil.copystat(source, dest, follow_symlinks=False)
        written.append(dest)
    return written


def emit_bundles_verbatim(
    marketplace_dir: Path,
    output_dir: Path,
    bundles: Iterable[str] | None = None,
) -> list[Path]:
    """Convenience wrapper — mirror every selected bundle."""
    bundle_list = list(bundles) if bundles is not None else None
    written: list[Path] = []
    for bundle_dir in iter_bundle_dirs(marketplace_dir, bundle_list):
        written.extend(emit_bundle_verbatim(bundle_dir, output_dir))
    return written
