# SPDX-License-Identifier: FSL-1.1-ALv2
"""Structural vocabulary excluded from banner attribution."""

#: Tokens too generic to attribute anything by. A banner whose only tokens are
#: these names no subject, and a construct matching only on one of them would
#: match nearly every heading.
_STOPWORDS = frozenset(
    {
        'and',
        'the',
        'for',
        'not',
        'with',
        'from',
        'into',
        'this',
        'that',
        'rule',
        'rules',
        'helper',
        'helpers',
        'shared',
        'common',
        'util',
        'utils',
        'test',
        'tests',
        'main',
        # Structural section vocabulary. Nearly every module carries several of
        # these across several headings, so they attribute nothing on their own —
        # and leaving them in is what turns the check into a false-positive machine.
        'entry',
        'point',
        'points',
        'public',
        'private',
        'internal',
        'scanner',
        'scan',
        'parsing',
        'parser',
        'derivation',
        'detection',
        'data',
        'class',
        'classes',
        'form',
        'file',
        'files',
        'source',
        'population',
        'finding',
        'findings',
        'construction',
        'pattern',
        'patterns',
        'check',
        'checks',
        'side',
        'state',
        'states',
        'line',
        'lines',
        'per',
        'model',
        'output',
        'input',
        'result',
        'results',
        'config',
        'configuration',
        'module',
        'modules',
    }
)
