# SPDX-License-Identifier: FSL-1.1-ALv2
"""Recogniser and constant boundaries for ``_chat_provenance``.

The predicate rests on three recognisers — the skill-load marker, the markdown
heading that must follow it, and the tag grammar — plus the literal notice
prefixes. Each decides whether a real operator turn survives, and each is a
place where a one-character change flips the classification without failing
anything else.

The predicate's own behaviour is covered in ``test_platform_runtime_chat_provenance.py``.
"""

from __future__ import annotations

import _chat_provenance as _mod


class TestPublishedConstants:
    """The notice prefixes are pinned to their literal values.

    A test that reads a constant back from the module under test cannot see
    that constant change — the list shrinks and the loop shrinks with it. That
    is this plan's own thesis ("a named list is a sample") applied to its own
    tests, and it is why each value below is written out rather than iterated.

    The module's other constants are pinned where their behaviour is exercised:
    ``_SKILL_LOAD_MARKER`` and ``_MARKDOWN_HEADING_RE`` in
    :class:`TestRecogniserBoundaries` below, and ``OPERATOR_BEARING_TAGS`` and
    ``_TAG_RE``'s attribute class in ``test_platform_runtime_chat_provenance.py``.
    Nothing enforces that this list stays complete — it is maintained by hand, so
    a constant added later is covered only if someone adds a case for it.
    """

    def test_harness_notice_prefixes_are_the_observed_literals(self):
        assert _mod.HARNESS_NOTICE_PREFIXES == (
            'This session is being continued from a previous conversation',
            'Caveat: The messages below were generated by the user while running local commands',
            'Stop hook feedback:',
        )

    def test_each_notice_prefix_drops_its_turn(self):
        """Named individually, so deleting one from the tuple fails here."""
        for notice in (
            'This session is being continued from a previous conversation',
            'Caveat: The messages below were generated by the user while running local commands',
            'Stop hook feedback:',
        ):
            assert _mod.is_operator_authored(f'{notice} — and the rest of it') is False


class TestRecogniserBoundaries:
    """The two private regexes decide what counts as a heading and as a tag.

    Neither is a published name, so neither is covered by the constant pinning
    above; both nonetheless carry behaviour an operator turn depends on.
    """

    def test_a_hash_prefixed_non_heading_line_is_not_a_markdown_heading(self):
        """A heading needs whitespace after the hashes.

        Without that, a shebang or a `#include` turns any turn quoting the
        skill-load marker into an "injected skill body" — discarding a real
        operator question. The "and text" half is pinned separately by
        :meth:`test_a_heading_needs_text_after_the_hashes`.
        """
        text = (
            'why does the log say "Base directory for this skill: /tmp/x"?\n'
            'my hook starts with\n'
            '#!/usr/bin/env bash\n'
            'and never runs'
        )
        assert _mod.is_synthetic_skill_load(text) is False
        assert _mod.is_operator_authored(text) is True

    def test_the_skill_load_marker_includes_its_trailing_colon(self):
        """The marker is a literal, and its exact form decides the match.

        Truncating it makes ordinary prose beginning "Base directory for this
        skill is wrong" read as an injected body whenever a heading follows.
        """
        assert _mod._SKILL_LOAD_MARKER == 'Base directory for this skill:'
        text = 'Base directory for this skill is wrong\n\n# what I tried\n\nplease revert'
        assert _mod.is_synthetic_skill_load(text) is False

    def test_the_heading_must_follow_the_first_marker_occurrence(self):
        """The scan starts at the FIRST marker, not the last.

        Searching from the last occurrence lets an injected body whose heading
        sits between two marker lines escape recognition.
        """
        text = (
            'Base directory for this skill: /a\n\n# Demo Skill\n\nbody body body\n'
            'Base directory for this skill: /b'
        )
        assert _mod.is_synthetic_skill_load(text) is True

    def test_a_heading_needs_hashes_at_line_start(self):
        """A `#` mid-line is not a heading — the pattern is anchored."""
        text = 'why does "Base directory for this skill: /tmp/x" appear? see issue # 42'
        assert _mod.is_synthetic_skill_load(text) is False
        assert _mod.is_operator_authored(text) is True

    def test_a_heading_needs_text_after_the_hashes(self):
        """Hashes and whitespace alone do not open a skill body."""
        text = 'Base directory for this skill: /tmp/x — what is this?\n#   '
        assert _mod.is_synthetic_skill_load(text) is False
        assert _mod.is_operator_authored(text) is True

    def test_heading_levels_one_through_six_are_headings(self):
        """Every ATX level opens an injected body; seven hashes does not."""
        for level in range(1, 7):
            body = f'Base directory for this skill: /x\n\n{"#" * level} Demo\n\nbody'
            assert _mod.is_synthetic_skill_load(body) is True, level
        seven = 'Base directory for this skill: /x\n\n####### not a heading\n\nplease revert'
        assert _mod.is_synthetic_skill_load(seven) is False

    def test_a_heading_may_carry_extra_space_before_its_text(self):
        """`#  Demo` is a heading; the separator is one-or-more whitespace."""
        text = 'Base directory for this skill: /x\n\n#  Demo Skill\n\nbody'
        assert _mod.is_synthetic_skill_load(text) is True

    def test_a_tag_name_must_start_with_a_letter(self):
        """`<2>…</2>` is prose, not a harness envelope.

        Admitting digit-led names empties the residue of a turn whose only
        markup is something like a numbered placeholder.
        """
        assert _mod.is_operator_authored('<2>revert the rename</2>') is True

    def test_the_residue_is_a_concatenation_not_a_join(self):
        """Stripping an envelope must not insert a separator.

        `strip_harness_envelopes` returns the residue in document order; adding
        whitespace between the surviving fragments splits a harness notice that
        an envelope interrupts, so it stops matching its prefix and the turn
        scores as operator.
        """
        assert _mod.strip_harness_envelopes('Stop hook <a/>feedback:') == 'Stop hook feedback:'
        assert _mod.is_operator_authored('Stop hook <a/>feedback:') is False

    def test_a_tag_name_may_not_start_with_an_underscore(self):
        """`<_x>` is prose, not an envelope."""
        assert _mod.is_operator_authored('<_x>please revert that change</_x>') is True

    def test_a_double_slash_close_tag_does_not_pair(self):
        """`</​/a>` is malformed and must not close `<a>`."""
        assert _mod.is_operator_authored('<a><//a>') is True

    def test_a_dotted_tag_name_pairs_only_with_itself(self):
        """Dots are part of the name, so `<a.b>` and `</a.c>` are not a pair.

        Dropping the dot from the name class both breaks that pairing and lets
        a non-allow-listed `<command-args.x>` recover its inner text as an
        operator instruction.
        """
        assert _mod.is_operator_authored('<a.b>please revert</a.c>') is True
        nested = '<command-args.x>please revert that change</command-args.x>'
        assert _mod.is_operator_authored(nested) is False
