#!/usr/bin/env python3
# SPDX-License-Identifier: FSL-1.1-ALv2
"""Atomic finalize move-back: integrate the worktree-resident plan into main.

Notation: ``plan-marshall:workflow-integration-git:integrate_into_main``

This is a single-action standalone script that, in ONE atomic call, performs the
finalize integration step of the move-based, cwd-pinned hermetic worktree model
(ADR-002, solution_outline.md §5). It is the inverse of the D4 move-in script
(``prepare_execute.py``) and runs while the worktree is STILL PRESENT — branch
cleanup removes the worktree AFTER this script returns. In one call it:

  1. **ACQUIRES** the cooperative merge lock (delegating to the unified
     ``plan-marshall:manage-locks:merge_lock`` script — atomic ``O_EXCL`` create,
     holder = this ``plan_id``, simple-backoff retry, plan-liveness stale
     reclamation). The merge lock is the SINGLE deliberate main-anchored
     exception to cwd-relative resolution (ADR-002).
  2. **FOLDS** the plan's OWN global logs (only logs generated for this plan,
     currently resident in the worktree's ``.plan/local/logs/``) into the plan
     directory (``.plan/local/plans/{plan_id}/logs/``) BEFORE move-back so the
     retrospective can read them after the plan dir lands on main.
  3. **MOVES** the plan directory back from the worktree to the main checkout.
  4. **RELEASES** the merge lock — on EVERY exit path, including the rollback
     path, so a crashed-and-retried finalize never wedges the lock.

The on-main executor is NOT regenerated here. Regeneration is a project-level,
meta-project-only finalize step (``finalize-step-sync-plugin-cache``, run after
the cache sync) — only the plan-marshall meta-project's own plans ever modify
``marketplace/bundles/*/skills/*/scripts/``, so only that project ever needs the
on-main executor mapping rebuilt. The executor is a per-tree DERIVED artifact
(ADR-002), never a moved slot and never regenerated by this shipped script.

It RETURNS a status TOON; it does NOT change the caller's cwd (a subprocess
cannot mutate its parent's cwd) and it does NOT remove the worktree (branch
cleanup owns that, after this returns). The finalize orchestrator returns ITS OWN
cwd to main after the call (so the uniform cwd rule resumes main resolution for
retrospective + archive).

SOURCE and DESTINATION are resolved **cwd-independently** so the verb is correct
from ANY cwd (worktree or main): the SOURCE worktree path is resolved via the
canonical ``manage-status get-worktree-path`` channel with a structural
``get_worktree_root() / {plan_id}`` filesystem-probe fallback for the
moved-in-from-main case (the plan dir MOVED off main into its worktree at
phase-5, so the channel's status.json read on main returns NOT_FOUND), mirroring
``git-workflow.py``'s ``cmd_locate_plan_checkout``; the DESTINATION
main plan dir is resolved via the single sanctioned main-anchored resolver
``resolve_main_anchored_path('plans/{plan_id}')`` (ADR-002). Neither resolution
depends on the process cwd, so the idempotence guard returns ``noop`` ONLY when
the SOURCE is genuinely absent AND an AUTHORITATIVE (``status.json``-bearing)
main DESTINATION is present. A ``status.json``-less orphan slot at the
destination (``logs/``/``work/`` residue only) is reclaimed by the move-back,
not treated as a completed integration.

Atomic-with-rollback (solution_outline.md §5): a partial move-back failure rolls
the plan dir BACK into the worktree so the authoritative copy is never split, and
the merge lock is released on the rollback path too. Idempotent: an
already-moved-back plan (real plan dir already resident on main, none in the
worktree) is a no-op success.

See the TOCTOU / check-then-act mitigation menu in
``ref-code-quality/standards/code-organization.md#toctou--check-then-act-hazards``
and the lock-correctness notes in ``manage-locks/scripts/merge_lock.py``.
"""

from __future__ import annotations

import importlib.util
import os
import shutil
import subprocess
import sys
from argparse import Namespace
from pathlib import Path
from typing import Any

from file_ops import (
    get_executor_path,
    get_worktree_root,
)
from marketplace_paths import (
    PLAN_DIR_NAME,
    resolve_main_anchored_path,
)
from toon_parser import parse_toon
from triage_helpers import (
    ErrorCode,
    create_workflow_cli,
    make_error,
    print_toon,
    safe_main,
)

# ---------------------------------------------------------------------------
# Cross-skill script delegation (kebab-case filenames → importlib by file path)
# ---------------------------------------------------------------------------
# merge_lock.py is loaded by file path so this script reuses the SINGLE owner of
# lock logic (the unified manage-locks merge mutex) rather than re-implementing
# it. The unified merge_lock now lives under manage-locks/scripts/ (reconciled
# from the former workflow-integration-git copy + the status-marker scan), so the
# load path resolves a sibling skill's scripts dir, not this skill's own.

_THIS_DIR = Path(__file__).resolve().parent
_MERGE_LOCK_PATH = (
    _THIS_DIR.parent.parent / 'manage-locks' / 'scripts' / 'merge_lock.py'
)


def _load_module_by_path(name: str, path: Path) -> Any:
    """Import a module by file path (used for sibling scripts)."""
    spec = importlib.util.spec_from_file_location(name, path)
    if spec is None or spec.loader is None:
        raise RuntimeError(f'cannot load {name} from {path}')
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def _load_merge_lock() -> Any:
    """Import ``merge_lock.py`` by file path."""
    return _load_module_by_path('merge_lock', _MERGE_LOCK_PATH)


# ---------------------------------------------------------------------------
# cwd-independent SOURCE worktree-path resolution
# ---------------------------------------------------------------------------
# Resolves the SOURCE worktree path so the move-back is correct from ANY cwd
# (worktree or main). Two resolution paths are tried in order, mirroring the
# sibling git-workflow.py ``cmd_locate_plan_checkout``:
#   1. The canonical ``manage-status get-worktree-path`` channel, which reads
#      ``status.metadata.worktree_path`` from the plan's ``status.json``. This
#      succeeds for a not-yet-moved plan whose status.json is still on main.
#   2. A structural ``get_worktree_root() / {plan_id}`` filesystem probe for the
#      moved-in-from-main case: under the ADR-002 move model the plan dir is
#      MOVED off main into its worktree at phase-5, so the manage-status channel
#      (reading main's now-absent status.json) returns NOT_FOUND. The probe
#      confirms status.json at the canonical worktree layout on disk directly.
# Genuine infrastructure failures (executor missing, timeout, parse error) and
# the genuine "no worktree / plan absent" outcome still surface as NOT_FOUND.

# Expected-error substrings: a manage-status error whose message contains one of
# these is the recoverable "channel could not resolve" case (no worktree
# configured / status.json missing), which the structural probe rescues. Any
# other error is a critical infrastructure failure surfaced verbatim.
_EXPECTED_ERROR_SUBSTRINGS = (
    'no worktree configured',
    'not found',
    'does not exist',
    'use_worktree is false',
    'worktree_path is unset',
)


def _resolve_worktree_path_via_status_channel(
    plan_id: str,
) -> tuple[Path | None, dict | None]:
    """Resolve the worktree path via the ``manage-status get-worktree-path`` channel.

    Returns ``(path, None)`` on success, ``(None, error_dict)`` on failure. The
    error dict is a fully-formed TOON-shaped payload (``NOT_FOUND`` code). A
    caller that wants the structural fallback inspects the error message against
    :data:`_EXPECTED_ERROR_SUBSTRINGS` to distinguish a recoverable
    channel-could-not-resolve case from a critical infrastructure failure.
    """
    try:
        executor = get_executor_path()
    except RuntimeError as exc:
        return None, make_error(
            f'cannot resolve plan-marshall executor: {exc}',
            code=ErrorCode.NOT_FOUND,
            plan_id=plan_id,
        )
    if not executor.exists():
        return None, make_error(
            'plan-marshall executor not available (.plan/execute-script.py missing)',
            code=ErrorCode.NOT_FOUND,
            plan_id=plan_id,
        )

    try:
        result = subprocess.run(
            [
                'python3',
                str(executor),
                'plan-marshall:manage-status:manage-status',
                'get-worktree-path',
                '--plan-id',
                plan_id,
            ],
            capture_output=True,
            text=True,
            timeout=30,
        )
    except (FileNotFoundError, subprocess.TimeoutExpired) as exc:
        return None, make_error(
            f'manage-status get-worktree-path failed: {exc}',
            code=ErrorCode.NOT_FOUND,
            plan_id=plan_id,
        )

    if result.returncode != 0:
        return None, make_error(
            (result.stderr or result.stdout).strip()
            or 'manage-status get-worktree-path failed',
            code=ErrorCode.NOT_FOUND,
            plan_id=plan_id,
        )

    try:
        parsed = parse_toon(result.stdout)
    except Exception as exc:  # noqa: BLE001 — defensive against TOON drift
        return None, make_error(
            f'failed to parse manage-status output: {exc}',
            code=ErrorCode.NOT_FOUND,
            plan_id=plan_id,
        )

    if parsed.get('status') == 'error' or parsed.get('error'):
        return None, make_error(
            parsed.get('message') or 'manage-status reported an error',
            code=ErrorCode.NOT_FOUND,
            plan_id=plan_id,
        )

    use_worktree = bool(parsed.get('use_worktree'))
    worktree_path_value = parsed.get('worktree_path') or ''
    if not use_worktree or not worktree_path_value:
        return None, make_error(
            'No worktree configured for this plan — '
            'status.metadata.use_worktree is false or worktree_path is unset',
            code=ErrorCode.NOT_FOUND,
            plan_id=plan_id,
        )

    return Path(str(worktree_path_value)), None


def _structural_worktree_probe(plan_id: str) -> Path | None:
    """Probe the canonical ``get_worktree_root() / {plan_id}`` location on disk.

    Returns the worktree path when ``status.json`` is present at the canonical
    ``{plan_id}/.plan/local/plans/{plan_id}/status.json`` layout, else ``None``.
    Outside a git repo (``get_worktree_root`` raises ``RuntimeError``) there is
    no worktree root to probe, so the probe yields ``None``.
    """
    try:
        candidate = get_worktree_root() / plan_id
    except RuntimeError:
        return None
    status_json = candidate / PLAN_DIR_NAME / 'local' / 'plans' / plan_id / 'status.json'
    if status_json.is_file():
        return candidate
    return None


def _resolve_worktree_path_for_plan(plan_id: str) -> tuple[Path | None, dict | None]:
    """Resolve ``status.metadata.worktree_path`` for ``plan_id`` cwd-independently.

    Returns ``(path, None)`` on success, ``(None, error_dict)`` on failure. The
    error dict is a fully-formed TOON-shaped payload ready to return from the
    handler. Resolution tries the canonical ``manage-status get-worktree-path``
    channel first, then a structural ``get_worktree_root() / {plan_id}``
    filesystem probe for the moved-in-from-main case (the plan dir MOVED off main
    into its worktree at phase-5, ADR-002, so the channel's status.json read on
    main returns NOT_FOUND). Critical infrastructure failures still surface
    verbatim; only the recoverable channel-could-not-resolve case is rescued by
    the probe.
    """
    path, error = _resolve_worktree_path_via_status_channel(plan_id)
    if path is not None:
        return path, None

    # The channel could not resolve. Propagate a critical infrastructure failure
    # verbatim; rescue only the recoverable channel-could-not-resolve case (no
    # worktree configured / status.json missing — the moved-in-from-main case)
    # via the structural probe.
    assert error is not None  # noqa: S101 — channel returns an error when path is None
    # ``make_error`` (triage_helpers) stores the human-readable text under the
    # ``error`` key, NOT ``message`` — read ``error`` first so the recoverable
    # channel-could-not-resolve case is actually detected (a ``message``-only read
    # always saw '' and made the structural-probe fallback unreachable). Keep
    # ``message`` as a defensive fallback for any non-``make_error`` payload shape.
    msg = str(error.get('error') or error.get('message') or '').lower()
    if not any(s in msg for s in _EXPECTED_ERROR_SUBSTRINGS):
        return None, error

    probed = _structural_worktree_probe(plan_id)
    if probed is not None:
        return probed, None

    # Neither the channel nor the structural probe resolved the worktree — the
    # genuine "no worktree / plan absent" outcome. Surface the channel's error.
    return None, error


# ---------------------------------------------------------------------------
# move-back primitives (inverse of prepare_execute._move_in_slot)
# ---------------------------------------------------------------------------


def _is_real_resident(path: Path) -> bool:
    """Return True when ``path`` is a real (non-symlink) materialized path."""
    return path.exists() and not path.is_symlink()


def _is_authoritative_dir(path: Path) -> bool:
    """Return True when ``path`` is an authoritative plan dir.

    The ``status.json`` sentinel marks a real, initialized plan directory. An
    authoritative destination must NEVER be clobbered by the move-back.
    """
    return (path / 'status.json').is_file()


def _is_reclaimable_orphan(path: Path) -> bool:
    """Return True when ``path`` is a non-authoritative orphan slot.

    A reclaimable orphan is a real (non-symlink) directory that lacks the
    ``status.json`` sentinel — typically a ``logs/``/``work/``-only residue
    materialized by a mis-resolved metrics/logging write while the authoritative
    plan dir was worktree-resident. Such a slot may be safely absorbed and
    removed before the move-back.
    """
    return _is_real_resident(path) and not _is_authoritative_dir(path)


def _absorb_orphan_contents(orphan: Path, src: Path) -> None:
    """Best-effort absorb a reclaimable orphan's residue into ``src``.

    Merges the orphan destination's stale ``logs/`` and ``work/`` contents into
    the worktree-resident plan dir ``src`` about to be moved in, so no plan-own
    log/work residue is lost when the orphan slot is reclaimed. Each file is
    copied only when no same-named file already exists under ``src`` (the
    worktree-resident copy is authoritative and wins on collision).
    """
    for subdir in ('logs', 'work'):
        orphan_sub = orphan / subdir
        if not orphan_sub.is_dir():
            continue
        dst_sub = src / subdir
        dst_sub.mkdir(parents=True, exist_ok=True)
        for entry in sorted(orphan_sub.iterdir()):
            if not entry.is_file():
                continue
            target = dst_sub / entry.name
            if target.exists():
                continue
            try:
                shutil.copy2(str(entry), str(target))
            except OSError:
                pass


def _move_back_dir(src: Path, dst: Path) -> None:
    """Move the plan dir ``src`` (worktree-resident) to ``dst`` (main).

    Replaces any symlink/stale placeholder at ``dst`` first (the worktree-create
    step left a symlink at main's slot pointing into the worktree; under the
    move model that is reversed at finalize). The destination's parent is created
    on demand.

    A ``status.json``-less orphan at ``dst`` (a ``logs/``/``work/``-only residue,
    not an authoritative plan dir) is RECLAIMED: its stale residue is absorbed
    into ``src`` and the emptied slot is removed before the move proceeds. An
    AUTHORITATIVE destination (``status.json`` present) is refused rather than
    clobbered.
    """
    if dst.is_symlink():
        dst.unlink()
    elif dst.exists():
        if _is_authoritative_dir(dst):
            # A real, initialized plan dir already occupies main's slot — refuse
            # rather than clobber. The idempotence guard short-circuits the
            # already-moved-back case before reaching here, so an authoritative
            # dst here is an unexpected collision.
            raise FileExistsError(f'main plan-dir slot already occupied by real path: {dst}')
        # Reclaimable orphan: absorb its stale logs/work residue into the
        # worktree-resident plan dir, then remove the emptied slot.
        _absorb_orphan_contents(dst, src)
        shutil.rmtree(str(dst))
    dst.parent.mkdir(parents=True, exist_ok=True)
    shutil.move(str(src), str(dst))


def _restore_to_worktree(src: Path, dst: Path) -> None:
    """Best-effort inverse of :func:`_move_back_dir` for rollback.

    Moves a successfully-moved ``dst`` (main) back to ``src`` (worktree) so a
    partial failure leaves the authoritative plan copy WHOLLY in the worktree.
    Swallows errors — rollback runs on the error path and must not mask the
    original failure.
    """
    try:
        if _is_real_resident(dst) and not src.exists():
            src.parent.mkdir(parents=True, exist_ok=True)
            shutil.move(str(dst), str(src))
    except OSError:
        pass


# ---------------------------------------------------------------------------
# Fold the plan's own global logs into the plan dir
# ---------------------------------------------------------------------------


def _fold_global_logs(wt_global_logs: Path, plan_logs_dst: Path) -> list[str]:
    """Fold the worktree-resident global logs into the plan dir's ``logs/``.

    The plan's OWN global logs accumulate in the worktree's
    ``.plan/local/logs/`` during phase-5+ execution. Folding them into the plan
    dir BEFORE move-back makes them resident on main alongside the plan after
    integration, so the retrospective LOG step reads them from the plan dir.

    Best-effort and non-fatal: a missing/empty global-logs dir is a no-op. Each
    log file is COPIED (not moved) into ``<plan_dir>/logs/`` so the worktree's
    own copy is left intact for the worktree-removal step. Returns the list of
    folded-in log filenames (for the status payload).
    """
    folded: list[str] = []
    if not wt_global_logs.is_dir():
        return folded
    plan_logs_dst.mkdir(parents=True, exist_ok=True)
    for entry in sorted(wt_global_logs.iterdir()):
        if not entry.is_file():
            continue
        try:
            shutil.copy2(str(entry), str(plan_logs_dst / entry.name))
            folded.append(entry.name)
        except OSError:
            # A single un-copyable log never blocks finalize integration.
            continue
    return folded


# ---------------------------------------------------------------------------
# main action
# ---------------------------------------------------------------------------


def run_integrate_into_main(args: Namespace) -> dict[str, Any]:
    """Acquire lock → fold logs → move-back → release (one action).

    Returns a TOON-shaped payload carrying ``status``. Never changes the caller's
    cwd; never removes the worktree; never regenerates the executor. The merge
    lock is released on EVERY exit path, including rollback.
    """
    plan_id: str = args.plan_id

    cwd_at_entry = os.getcwd()

    def _assert_cwd_unchanged(payload: dict[str, Any]) -> dict[str, Any]:
        """Defensive self-check: this script must never mutate the caller cwd."""
        if os.getcwd() != cwd_at_entry:
            os.chdir(cwd_at_entry)
            return make_error(
                'integrate_into_main changed the process cwd (invariant violation); restored',
                code=ErrorCode.INVALID_INPUT,
                plan_id=plan_id,
            )
        return payload

    # Resolve the worktree-resident SOURCE and the main DESTINATION
    # cwd-independently, so the verb is correct from ANY cwd (worktree or main).
    # SOURCE: the canonical manage-status get-worktree-path channel. DESTINATION:
    # the single sanctioned main-anchored resolver (ADR-002).
    worktree_path, wt_err = _resolve_worktree_path_for_plan(plan_id)
    if wt_err is not None:
        return _assert_cwd_unchanged(wt_err)
    assert worktree_path is not None  # noqa: S101 — narrow for type-checker

    try:
        main_plan_dir = resolve_main_anchored_path(f'plans/{plan_id}')
    except RuntimeError as exc:
        return _assert_cwd_unchanged(
            make_error(
                f'cannot resolve main plan directory: {exc}',
                code=ErrorCode.NOT_FOUND,
                plan_id=plan_id,
            )
        )
    wt_plan_dir = worktree_path / PLAN_DIR_NAME / 'local' / 'plans' / plan_id
    wt_global_logs = worktree_path / PLAN_DIR_NAME / 'local' / 'logs'

    # --- Idempotence guard -------------------------------------------------
    # If an AUTHORITATIVE plan dir (status.json present) is already resident on
    # main AND no real plan dir remains in the worktree, the move-back already
    # ran (a finalize re-entry). Return a no-op success WITHOUT acquiring the
    # lock — there is nothing to coordinate. A status.json-less orphan at main
    # (logs/work residue only) is NOT a completed integration: it falls through
    # to the reclaiming move-back below rather than short-circuiting as noop.
    if _is_authoritative_dir(main_plan_dir) and not _is_real_resident(wt_plan_dir):
        return _assert_cwd_unchanged(
            {
                'status': 'success',
                'plan_id': plan_id,
                'action': 'noop',
                'message': 'plan state already integrated into main',
            }
        )

    # The worktree-resident plan dir MUST exist to move it back. Its absence
    # (and the main dir also absent) means the plan was never moved in or the
    # state is in an unexpected shape — fail loud rather than fabricate.
    if not _is_real_resident(wt_plan_dir):
        return _assert_cwd_unchanged(
            make_error(
                f'worktree-resident plan directory not found: {wt_plan_dir}',
                code=ErrorCode.NOT_FOUND,
                plan_id=plan_id,
            )
        )

    # --- Step 1: acquire the cooperative merge lock ------------------------
    # set_title_token=False suppresses the merge lock's terminal-title glyph
    # surface (⏳/🔒): the move-back lock is a brief, finalize-internal mutex, so
    # flashing a lock glyph into the title is spurious noise the user never needs
    # to see. The token is a display affordance, not a correctness primitive.
    merge_lock = _load_merge_lock()
    acquire_result = merge_lock.run_acquire(
        Namespace(plan_id=plan_id, timeout=None, set_title_token=False)
    )
    if acquire_result.get('status') != 'success':
        # Could not acquire (timeout / resolution failure) — surface verbatim.
        # No lock was acquired, so there is nothing to release.
        return _assert_cwd_unchanged({**acquire_result, 'plan_id': plan_id})

    def _release_and(payload: dict[str, Any]) -> dict[str, Any]:
        """Release the lock (idempotent) and return ``payload`` unchanged."""
        try:
            # set_title_token=False mirrors the acquire above — the move-back
            # lock never set a title token, so there is nothing to clear.
            merge_lock.run_release(Namespace(plan_id=plan_id, set_title_token=False))
        except Exception:  # noqa: BLE001 - release must never mask the real result
            # Release failure is logged via the lock's own contract on the next
            # acquire's stale-reclamation path; never let it overwrite the
            # operation's real status.
            pass
        return _assert_cwd_unchanged(payload)

    # --- Step 2: fold the plan's own global logs into the plan dir ---------
    # Folded BEFORE move-back so they travel with the plan dir to main. Folds
    # into the WORKTREE-resident plan dir's logs/ (the dir we are about to move).
    folded_logs = _fold_global_logs(wt_global_logs, wt_plan_dir / 'logs')

    # --- Step 3: move the plan directory back to main (atomic w/ rollback) --
    try:
        _move_back_dir(wt_plan_dir, main_plan_dir)
    except (OSError, FileExistsError) as exc:
        # Roll the plan dir back into the worktree so the authoritative copy is
        # never split, then release the lock.
        _restore_to_worktree(wt_plan_dir, main_plan_dir)
        return _release_and(
            make_error(
                f'move-back failed for {wt_plan_dir} -> {main_plan_dir}: {exc}; '
                f'rolled back to worktree',
                code=ErrorCode.INVALID_INPUT,
                plan_id=plan_id,
            )
        )

    # --- Step 4: release the lock and return success ------------------------
    # The on-main executor is NOT regenerated here — that is the project-level
    # finalize-step-sync-plugin-cache step's responsibility (meta-project-only),
    # run after the cache sync.
    return _release_and(
        {
            'status': 'success',
            'plan_id': plan_id,
            'action': 'integrated',
            'plan_dir': str(main_plan_dir),
            'folded_logs': folded_logs,
        }
    )


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------


def main() -> int:
    """Entry point — single ``integrate`` action."""
    parser = create_workflow_cli(
        description=(
            'Atomic finalize move-back: acquire lock, fold logs, move plan dir to '
            'main, release lock'
        ),
        epilog="""
Examples:
  integrate_into_main.py integrate --plan-id EXAMPLE-PLAN
""",
        subcommands=[
            {
                'name': 'integrate',
                'help': (
                    'Atomically integrate the worktree-resident plan into main '
                    '(lock → fold-logs → move-back → release)'
                ),
                'handler': run_integrate_into_main,
                'args': [
                    {
                        'flags': ['--plan-id'],
                        'dest': 'plan_id',
                        'required': True,
                        'help': 'Plan identifier (mandatory)',
                    },
                ],
            },
        ],
    )
    args = parser.parse_args()
    return print_toon(args.func(args))


if __name__ == '__main__':
    sys.exit(safe_main(main))
