#!/usr/bin/env python3
"""Atomic finalize move-back: integrate the worktree-resident plan into main.

Notation: ``plan-marshall:workflow-integration-git:integrate_into_main``

This is a single-action standalone script that, in ONE atomic call, performs the
finalize integration step of the move-based, cwd-pinned hermetic worktree model
(ADR-002, solution_outline.md §5). It is the inverse of the D4 move-in script
(``prepare_execute.py``) and runs while the worktree is STILL PRESENT — branch
cleanup removes the worktree AFTER this script returns. In one call it:

  1. **ACQUIRES** the cooperative merge lock (delegating to the D15 ``merge_lock``
     script — atomic ``O_EXCL`` create, holder = this ``plan_id``, simple-backoff
     retry, minimal stale reclamation). The merge lock is the SINGLE deliberate
     main-anchored exception to cwd-relative resolution (ADR-002).
  2. **FOLDS** the plan's OWN global logs (only logs generated for this plan,
     currently resident in the worktree's ``.plan/local/logs/``) into the plan
     directory (``.plan/local/plans/{plan_id}/logs/``) BEFORE move-back so the
     retrospective can read them after the plan dir lands on main.
  3. **MOVES** the plan directory back from the worktree to the main checkout.
  4. **RELEASES** the merge lock — on EVERY exit path, including the rollback
     path, so a crashed-and-retried finalize never wedges the lock.

The on-main executor is NOT regenerated here. Regeneration is a project-level,
meta-project-only finalize step (``finalize-step-sync-plugin-cache``, run after
the cache sync) — only the plan-marshall meta-project's own plans ever modify
``marketplace/bundles/*/skills/*/scripts/``, so only that project ever needs the
on-main executor mapping rebuilt. The executor is a per-tree DERIVED artifact
(ADR-002), never a moved slot and never regenerated by this shipped script.

It RETURNS a status TOON; it does NOT change the caller's cwd (a subprocess
cannot mutate its parent's cwd) and it does NOT remove the worktree (branch
cleanup owns that, after this returns). The finalize orchestrator returns ITS OWN
cwd to main after the call (so the uniform cwd rule resumes main resolution for
retrospective + archive).

SOURCE and DESTINATION are resolved **cwd-independently** so the verb is correct
from ANY cwd (worktree or main): the SOURCE worktree path is resolved via the
canonical ``manage-status get-worktree-path`` channel (mirroring
``git-workflow.py``'s ``_resolve_worktree_path_for_plan``), and the DESTINATION
main plan dir is resolved via the single sanctioned main-anchored resolver
``resolve_main_anchored_path('plans/{plan_id}')`` (ADR-002). Neither resolution
depends on the process cwd, so the idempotence guard returns ``noop`` ONLY when
the SOURCE is genuinely absent AND the main DESTINATION is present.

Atomic-with-rollback (solution_outline.md §5): a partial move-back failure rolls
the plan dir BACK into the worktree so the authoritative copy is never split, and
the merge lock is released on the rollback path too. Idempotent: an
already-moved-back plan (real plan dir already resident on main, none in the
worktree) is a no-op success.

See the TOCTOU / check-then-act mitigation menu in
``dev-general-code-quality/standards/code-organization.md#toctou--check-then-act-hazards``
and the lock-correctness notes in ``merge_lock.py``.
"""

from __future__ import annotations

import importlib.util
import os
import shutil
import subprocess
import sys
from argparse import Namespace
from pathlib import Path
from typing import Any

from file_ops import get_executor_path  # type: ignore[import-not-found]
from marketplace_paths import (  # type: ignore[import-not-found]
    PLAN_DIR_NAME,
    resolve_main_anchored_path,
)
from toon_parser import parse_toon  # type: ignore[import-not-found]
from triage_helpers import (  # type: ignore[import-not-found]
    ErrorCode,
    create_workflow_cli,
    make_error,
    print_toon,
    safe_main,
)

# ---------------------------------------------------------------------------
# Sibling-script delegation (kebab-case filenames → importlib by file path)
# ---------------------------------------------------------------------------
# merge_lock.py is loaded by file path so this script reuses the SINGLE owner of
# lock logic (merge_lock) rather than re-implementing it.

_THIS_DIR = Path(__file__).resolve().parent
_MERGE_LOCK_PATH = _THIS_DIR / 'merge_lock.py'


def _load_module_by_path(name: str, path: Path) -> Any:
    """Import a module by file path (used for sibling scripts)."""
    spec = importlib.util.spec_from_file_location(name, path)
    if spec is None or spec.loader is None:
        raise RuntimeError(f'cannot load {name} from {path}')
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def _load_merge_lock() -> Any:
    """Import ``merge_lock.py`` by file path."""
    return _load_module_by_path('merge_lock', _MERGE_LOCK_PATH)


# ---------------------------------------------------------------------------
# cwd-independent SOURCE worktree-path resolution
# ---------------------------------------------------------------------------
# Mirrors git-workflow.py's _manage_status_call + _resolve_worktree_path_for_plan:
# resolve the SOURCE worktree path via the canonical ``manage-status
# get-worktree-path`` channel so the move-back is correct regardless of caller
# cwd (the bug this script fixes — get_worktree_root() resolved cwd-relatively
# and produced a false noop when invoked from the worktree cwd).


def _resolve_worktree_path_for_plan(plan_id: str) -> tuple[Path | None, dict | None]:
    """Resolve ``status.metadata.worktree_path`` for ``plan_id`` cwd-independently.

    Returns ``(path, None)`` on success, ``(None, error_dict)`` on failure. The
    error dict is a fully-formed TOON-shaped payload ready to return from the
    handler. Resolution failure (executor missing, non-success TOON,
    ``use_worktree`` false, or empty ``worktree_path``) yields a
    ``NOT_FOUND`` / ``plan_resolution_failed`` error.
    """
    try:
        executor = get_executor_path()
    except RuntimeError as exc:
        return None, make_error(
            f'cannot resolve plan-marshall executor: {exc}',
            code=ErrorCode.NOT_FOUND,
            plan_id=plan_id,
        )
    if not executor.exists():
        return None, make_error(
            'plan-marshall executor not available (.plan/execute-script.py missing)',
            code=ErrorCode.NOT_FOUND,
            plan_id=plan_id,
        )

    try:
        result = subprocess.run(
            [
                'python3',
                str(executor),
                'plan-marshall:manage-status:manage-status',
                'get-worktree-path',
                '--plan-id',
                plan_id,
            ],
            capture_output=True,
            text=True,
            timeout=30,
        )
    except (FileNotFoundError, subprocess.TimeoutExpired) as exc:
        return None, make_error(
            f'manage-status get-worktree-path failed: {exc}',
            code=ErrorCode.NOT_FOUND,
            plan_id=plan_id,
        )

    if result.returncode != 0:
        return None, make_error(
            (result.stderr or result.stdout).strip()
            or 'manage-status get-worktree-path failed',
            code=ErrorCode.NOT_FOUND,
            plan_id=plan_id,
        )

    try:
        parsed = parse_toon(result.stdout)
    except Exception as exc:  # noqa: BLE001 — defensive against TOON drift
        return None, make_error(
            f'failed to parse manage-status output: {exc}',
            code=ErrorCode.NOT_FOUND,
            plan_id=plan_id,
        )

    if parsed.get('status') == 'error' or parsed.get('error'):
        return None, make_error(
            parsed.get('message') or 'manage-status reported an error',
            code=ErrorCode.NOT_FOUND,
            plan_id=plan_id,
        )

    use_worktree = bool(parsed.get('use_worktree'))
    worktree_path_value = parsed.get('worktree_path') or ''
    if not use_worktree or not worktree_path_value:
        return None, make_error(
            'No worktree configured for this plan — '
            'status.metadata.use_worktree is false or worktree_path is unset',
            code=ErrorCode.NOT_FOUND,
            plan_id=plan_id,
        )

    return Path(str(worktree_path_value)), None


# ---------------------------------------------------------------------------
# move-back primitives (inverse of prepare_execute._move_in_slot)
# ---------------------------------------------------------------------------


def _is_real_resident(path: Path) -> bool:
    """Return True when ``path`` is a real (non-symlink) materialized path."""
    return path.exists() and not path.is_symlink()


def _move_back_dir(src: Path, dst: Path) -> None:
    """Move the plan dir ``src`` (worktree-resident) to ``dst`` (main).

    Replaces any symlink/stale placeholder at ``dst`` first (the worktree-create
    step left a symlink at main's slot pointing into the worktree; under the
    move model that is reversed at finalize). The destination's parent is created
    on demand.
    """
    if dst.is_symlink():
        dst.unlink()
    elif dst.exists():
        # A real path already occupies main's slot — refuse rather than clobber.
        # The idempotence guard short-circuits the already-moved-back case before
        # reaching here, so a real dst here is an unexpected collision.
        raise FileExistsError(f'main plan-dir slot already occupied by real path: {dst}')
    dst.parent.mkdir(parents=True, exist_ok=True)
    shutil.move(str(src), str(dst))


def _restore_to_worktree(src: Path, dst: Path) -> None:
    """Best-effort inverse of :func:`_move_back_dir` for rollback.

    Moves a successfully-moved ``dst`` (main) back to ``src`` (worktree) so a
    partial failure leaves the authoritative plan copy WHOLLY in the worktree.
    Swallows errors — rollback runs on the error path and must not mask the
    original failure.
    """
    try:
        if _is_real_resident(dst) and not src.exists():
            src.parent.mkdir(parents=True, exist_ok=True)
            shutil.move(str(dst), str(src))
    except OSError:
        pass


# ---------------------------------------------------------------------------
# Fold the plan's own global logs into the plan dir
# ---------------------------------------------------------------------------


def _fold_global_logs(wt_global_logs: Path, plan_logs_dst: Path) -> list[str]:
    """Fold the worktree-resident global logs into the plan dir's ``logs/``.

    The plan's OWN global logs accumulate in the worktree's
    ``.plan/local/logs/`` during phase-5+ execution. Folding them into the plan
    dir BEFORE move-back makes them resident on main alongside the plan after
    integration, so the retrospective LOG step reads them from the plan dir.

    Best-effort and non-fatal: a missing/empty global-logs dir is a no-op. Each
    log file is COPIED (not moved) into ``<plan_dir>/logs/`` so the worktree's
    own copy is left intact for the worktree-removal step. Returns the list of
    folded-in log filenames (for the status payload).
    """
    folded: list[str] = []
    if not wt_global_logs.is_dir():
        return folded
    plan_logs_dst.mkdir(parents=True, exist_ok=True)
    for entry in sorted(wt_global_logs.iterdir()):
        if not entry.is_file():
            continue
        try:
            shutil.copy2(str(entry), str(plan_logs_dst / entry.name))
            folded.append(entry.name)
        except OSError:
            # A single un-copyable log never blocks finalize integration.
            continue
    return folded


# ---------------------------------------------------------------------------
# main action
# ---------------------------------------------------------------------------


def run_integrate_into_main(args: Namespace) -> dict[str, Any]:
    """Acquire lock → fold logs → move-back → release (one action).

    Returns a TOON-shaped payload carrying ``status``. Never changes the caller's
    cwd; never removes the worktree; never regenerates the executor. The merge
    lock is released on EVERY exit path, including rollback.
    """
    plan_id: str = args.plan_id

    cwd_at_entry = os.getcwd()

    def _assert_cwd_unchanged(payload: dict[str, Any]) -> dict[str, Any]:
        """Defensive self-check: this script must never mutate the caller cwd."""
        if os.getcwd() != cwd_at_entry:
            os.chdir(cwd_at_entry)
            return make_error(
                'integrate_into_main changed the process cwd (invariant violation); restored',
                code=ErrorCode.INVALID_INPUT,
                plan_id=plan_id,
            )
        return payload

    # Resolve the worktree-resident SOURCE and the main DESTINATION
    # cwd-independently, so the verb is correct from ANY cwd (worktree or main).
    # SOURCE: the canonical manage-status get-worktree-path channel. DESTINATION:
    # the single sanctioned main-anchored resolver (ADR-002).
    worktree_path, wt_err = _resolve_worktree_path_for_plan(plan_id)
    if wt_err is not None:
        return _assert_cwd_unchanged(wt_err)
    assert worktree_path is not None  # noqa: S101 — narrow for type-checker

    main_plan_dir = resolve_main_anchored_path(f'plans/{plan_id}')
    wt_plan_dir = worktree_path / PLAN_DIR_NAME / 'local' / 'plans' / plan_id
    wt_global_logs = worktree_path / PLAN_DIR_NAME / 'local' / 'logs'

    # --- Idempotence guard -------------------------------------------------
    # If the plan dir is already a real (non-symlink) path resident on main AND
    # no real plan dir remains in the worktree, the move-back already ran (a
    # finalize re-entry). Return a no-op success WITHOUT acquiring the lock —
    # there is nothing to coordinate.
    if _is_real_resident(main_plan_dir) and not _is_real_resident(wt_plan_dir):
        return _assert_cwd_unchanged(
            {
                'status': 'success',
                'plan_id': plan_id,
                'action': 'noop',
                'message': 'plan state already integrated into main',
            }
        )

    # The worktree-resident plan dir MUST exist to move it back. Its absence
    # (and the main dir also absent) means the plan was never moved in or the
    # state is in an unexpected shape — fail loud rather than fabricate.
    if not _is_real_resident(wt_plan_dir):
        return _assert_cwd_unchanged(
            make_error(
                f'worktree-resident plan directory not found: {wt_plan_dir}',
                code=ErrorCode.NOT_FOUND,
                plan_id=plan_id,
            )
        )

    # --- Step 1: acquire the cooperative merge lock ------------------------
    merge_lock = _load_merge_lock()
    acquire_result = merge_lock.run_acquire(Namespace(plan_id=plan_id, timeout=None))
    if acquire_result.get('status') != 'success':
        # Could not acquire (timeout / resolution failure) — surface verbatim.
        # No lock was acquired, so there is nothing to release.
        return _assert_cwd_unchanged({**acquire_result, 'plan_id': plan_id})

    def _release_and(payload: dict[str, Any]) -> dict[str, Any]:
        """Release the lock (idempotent) and return ``payload`` unchanged."""
        try:
            merge_lock.run_release(Namespace(plan_id=plan_id))
        except Exception:  # noqa: BLE001 - release must never mask the real result
            # Release failure is logged via the lock's own contract on the next
            # acquire's stale-reclamation path; never let it overwrite the
            # operation's real status.
            pass
        return _assert_cwd_unchanged(payload)

    # --- Step 2: fold the plan's own global logs into the plan dir ---------
    # Folded BEFORE move-back so they travel with the plan dir to main. Folds
    # into the WORKTREE-resident plan dir's logs/ (the dir we are about to move).
    folded_logs = _fold_global_logs(wt_global_logs, wt_plan_dir / 'logs')

    # --- Step 3: move the plan directory back to main (atomic w/ rollback) --
    try:
        _move_back_dir(wt_plan_dir, main_plan_dir)
    except (OSError, FileExistsError) as exc:
        # Roll the plan dir back into the worktree so the authoritative copy is
        # never split, then release the lock.
        _restore_to_worktree(wt_plan_dir, main_plan_dir)
        return _release_and(
            make_error(
                f'move-back failed for {wt_plan_dir} -> {main_plan_dir}: {exc}; '
                f'rolled back to worktree',
                code=ErrorCode.INVALID_INPUT,
                plan_id=plan_id,
            )
        )

    # --- Step 4: release the lock and return success ------------------------
    # The on-main executor is NOT regenerated here — that is the project-level
    # finalize-step-sync-plugin-cache step's responsibility (meta-project-only),
    # run after the cache sync.
    return _release_and(
        {
            'status': 'success',
            'plan_id': plan_id,
            'action': 'integrated',
            'plan_dir': str(main_plan_dir),
            'folded_logs': folded_logs,
        }
    )


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------


def main() -> int:
    """Entry point — single ``integrate`` action."""
    parser = create_workflow_cli(
        description=(
            'Atomic finalize move-back: acquire lock, fold logs, move plan dir to '
            'main, release lock'
        ),
        epilog="""
Examples:
  integrate_into_main.py integrate --plan-id EXAMPLE-PLAN
""",
        subcommands=[
            {
                'name': 'integrate',
                'help': (
                    'Atomically integrate the worktree-resident plan into main '
                    '(lock → fold-logs → move-back → release)'
                ),
                'handler': run_integrate_into_main,
                'args': [
                    {
                        'flags': ['--plan-id'],
                        'dest': 'plan_id',
                        'required': True,
                        'help': 'Plan identifier (mandatory)',
                    },
                ],
            },
        ],
    )
    args = parser.parse_args()
    return print_toon(args.func(args))


if __name__ == '__main__':
    sys.exit(safe_main(main))
